default_install_hook_types = ["pre-commit", "commit-msg"]

[[repos]]
repo = "local"

[[repos.hooks]]
id = "fmt"
name = "cargo fmt"
language = "system"
entry = "cargo fmt --all -- --check"
files = "\\.rs$"
pass_filenames = false

[[repos.hooks]]
id = "clippy"
name = "cargo clippy"
language = "system"
entry = "cargo clippy --all-targets --all-features -- -D warnings"
files = "\\.rs$"
pass_filenames = false

[[repos]]
repo = "https://github.com/alessandrojcm/commitlint-pre-commit-hook"
rev = "v9.21.0"

[[repos.hooks]]
id = "commitlint"
stages = ["commit-msg"]
additional_dependencies = ["@commitlint/config-conventional"]
